repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
        exclude: infra/helm/.*\.yaml$
      - id: debug-statements
        exclude: test/
      - id: destroyed-symlinks
      - id: end-of-file-fixer
        exclude: test/
        files: \.(py|sh|rst|yml|yaml)$
      - id: mixed-line-ending
      - id: trailing-whitespace
        files: \.(py|sh|rst|yml|yaml)$
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.6.8"
    hooks:
      - id: ruff
        args: [--config, pyproject.toml, --fix]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.991"
    hooks:
      - id: mypy
        args: [--config-file, pyproject.toml]
